USE management;

CREATE TABLE CUSTOMER(
   ID INT PRIMARY KEY auto_increment,
   IMAGE VARCHAR(1024),
   NAME VARCHAR(64),
   BIRTHDAY VARCHAR(64),
   GENDER VARCHAR(64),
   JOB VARCHAR(64)
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

INSERT INTO CUSTOMER (ID, IMAGE, NAME, BIRTHDAY, GENDER, JOB) VALUES (1, 'https://placeimg.com/64/64/1', 'GIL DONG HONG', '961222', 'MALE', 'STUDNET');
INSERT INTO CUSTOMER (ID, IMAGE, NAME, BIRTHDAY, GENDER, JOB) VALUES (2, 'https://placeimg.com/64/64/2', 'CHUL SOO KIM', '941222', 'MALE', 'DEVELOPER');
INSERT INTO CUSTOMER (ID, IMAGE, NAME, BIRTHDAY, GENDER, JOB) VALUES (3, 'https://placeimg.com/64/64/3', 'SOON HEE LEE', '921222', 'FEMALE', 'ENGINEER');


